AWSTemplateFormatVersion: '2010-09-09'
Description: Class template with CloudFormation

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00448a337adc93c05
      InstanceType: t2.micro
      KeyName: class-1 # <-- Change to use your key-pair name
      SecurityGroupIds: 
        - !Ref WebAppSecurityGroup
      Tags:
        -
          Key: Appplication
          Value:  red-yellow Server

  WebAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: webapp-security-group, class
      GroupDescription: "Allow HTTP/HTTPS and SSH inbound and outbound traffic"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
  MyKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName: class-1
